### ISSUE TITLE
Nested Schemas with methods fail to attach methods on null docs

### ISSUE THREAD

**Issue by Gary-Osteen-Q2** [teradonburi/mongoose-lean-methods#3]
When using lean methods on nested schemas, it fails to attach methods when parent document doesn't have a value for the nest document.

Error:
```
{
    "errorMessage": "Cannot set property 'doSomething' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot set property 'doSomething' of undefined",
        "    at attachMethodsToDoc (.../node_modules/mongoose-lean-methods/index.js:75:14)",
        "    at model.Query.attachMethods (.../node_modules/mongoose-lean-methods/index.js:48:18)",
        "    at model.Query.attachMethods (.../node_modules/mongoose-lean-methods/index.js:61:21)",
        "    at model.Query.<anonymous> (.../node_modules/mongoose-lean-methods/index.js:28:19)",
        "    at .../node_modules/mongoose-lean-methods/index.js:8:12",
        "    at .../node_modules/mongoose/lib/query.js:4429:15",

```

```
const childSchema = new Schema({ someField: String  })
childSchema.methods.doSomething = function () { return 'thing' }

const parentSchema = new Schema({ nestedArrayOfSchema: [childSchema] }

parenSchama.plugin(mongooseLeanMethods)
```

Old parentSchema doc
```
{
  unusedField: 'test',
  nestedArrayOfSchema: null
}
```

```
function attachMethodsToDoc(doc, methods) {
  if (!doc) return
  if (Object.keys(methods).length === 0) {
    return doc
  }
  for (const key in methods) {
    doc[key] = methods[key]
  }
  return doc
}
```
Adding the !doc check here fixes the issue.

**Comment by Gary-Osteen-Q2** [comment]
Opened this PR to fix this.
https://github.com/teradonburi/mongoose-lean-methods/pull/4

**Comment by teradonburi** [comment]
> Opened this PR to fix this.
> #4

I'm sorry too late response.
marged
